In [172]:
##import data
import pandas as pd
data=pd.read_csv('/Users/alfonsodamelio/Downloads/telekom.csv',delimiter=',')

In [173]:
#remove ids
data=data.drop(['ID'],axis=1)

In [174]:
data.dtypes

status                   int64
piano_tariff             int64
metodo_pagamento         int64
sesso                    int64
etacl                  float64
zona_attivaz             int64
canale_attivaz           int64
vas1                     int64
vas2                     int64
q01_out_ch_peak          int64
q01_out_dur_peak         int64
q01_out_val_peak       float64
q01_out_dur_offpeak      int64
q01_out_val_offpeak    float64
q01_in_ch_tot            int64
q01_in_dur_tot           int64
q01_ch_sms               int64
q09_out_ch_peak          int64
q09_out_dur_peak         int64
q09_out_val_peak       float64
q09_out_dur_offpeak      int64
q09_out_val_offpeak    float64
q09_in_ch_tot            int64
q09_in_dur_tot           int64
q09_ch_sms               int64
dtype: object

In [175]:
#find missing data
data.columns[data.isnull().any()].tolist()

[]

In [176]:
data.head(5)

status  piano_tariff  metodo_pagamento  sesso  etacl  zona_attivaz  \
0       0             8                 3      3  30.75             3   
1       0             8                 1      3  20.78             2   
2       0             7                 3      3  19.80             1   
3       0             8                 2      3  21.67             1   
4       0             8                 2      1  24.75             1   

   canale_attivaz  vas1  vas2  q01_out_ch_peak     ...      q01_in_dur_tot  \
0               5     1     1               45     ...                2162   
1               5     1     1                0     ...                   0   
2               5     1     1                0     ...                   0   
3               9     1     1                0     ...                   0   
4               5     1     1                0     ...                   0   

   q01_ch_sms  q09_out_ch_peak  q09_out_dur_peak  q09_out_val_peak  \
0           0               78              5190           34.6450   
1           0               11               719            4.8191   
2           0               50              2665           14.1168   
3           0               65              7216           43.6824   
4           0                0                 0            0.0000   

   q09_out_dur_offpeak  q09_out_val_offpeak  q09_in_ch_tot  q09_in_dur_tot  \
0                    0                  0.0            123           10715   
1                    0                  0.0             31            3115   
2                    0                  0.0            170           14807   
3                    0                  0.0             25            3334   
4                    0                  0.0              0               0   

   q09_ch_sms  
0           0  
1           1  
2           0  
3           0  
4           0  

[5 rows x 25 columns]

In [177]:
#separate X,y
X=data.drop(['status'],axis=1).values
y=data['status'].values

In [178]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [182]:
onehotencoder = OneHotEncoder(categorical_features = [0, 1, 2, 4, 5, 6, 7])
X = onehotencoder.fit_transform(X).toarray()

In [183]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [184]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [185]:
X

array([[  1.00000000e+00,   0.00000000e+00,   1.00000000e+00, ...,
          1.23000000e+02,   1.07150000e+04,   0.00000000e+00],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00, ...,
          3.10000000e+01,   3.11500000e+03,   1.00000000e+00],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00, ...,
          1.70000000e+02,   1.48070000e+04,   0.00000000e+00],
       ..., 
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00, ...,
          2.15000000e+02,   2.72570000e+04,   0.00000000e+00],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00, ...,
          2.23000000e+02,   1.72740000e+04,   0.00000000e+00],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00, ...,
          4.40000000e+01,   3.64600000e+03,   0.00000000e+00]])

In [186]:
# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split, cross_val_score
from sklearn.feature_selection import SelectKBest, chi2, f_classif

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [187]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
#scale the X coloumns
sc_X = StandardScaler()
#for the training set we need to fit it, then scale it
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

**Logistic Regression**

In [99]:
###############
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [102]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1043   37]
 [  46  633]]


In [103]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.95281409891984081

**SVC**

In [105]:
from sklearn.svm import SVC
#you can choose what type of kernel you want
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)


[[1039   41]
 [  40  639]]


0.953951108584423

**Gaussian Naive Bayes**

In [107]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)



[[988  92]
 [245 434]]


0.80841387151790789

In [110]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)



[[1049   31]
 [  15  664]]


0.97384877771461054

In [112]:
from sklearn.ensemble import GradientBoostingClassifier
classifier = GradientBoostingClassifier(loss="deviance",learning_rate = .5, 
                                  n_estimators = 1000,max_depth=2,min_samples_leaf=15,min_samples_split=40)
#min_samples_leaf=15
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

[[1057   23]
 [   9  670]]


0.98180784536668564

**BALANCED DATASET**

In [196]:
from imblearn.over_sampling import SMOTE
from sklearn.externals.joblib.parallel import _backend

sm = SMOTE(random_state=0, ratio = 1.0)
X, y = sm.fit_sample(X, y)


/anaconda/lib/python3.6/site-packages/sklearn/utils/deprecation.py:75: DeprecationWarning: Function _ratio_float is deprecated; Use a float for 'ratio' is deprecated from version 0.2. The support will be removed in 0.4. Use a dict, str, or a callable instead.
  warnings.warn(msg, category=DeprecationWarning)


In [204]:
# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
#scale the X coloumns
sc_X = StandardScaler()
#for the training set we need to fit it, then scale it
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)


**Logistic Regression**

In [205]:


###############
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

[[1008   49]
 [  31 1089]]


0.96325218190169959

In [208]:
from sklearn.ensemble import GradientBoostingClassifier
classifier = GradientBoostingClassifier(loss="deviance",learning_rate = .5, 
                                  n_estimators = 1000,max_depth=2,min_samples_leaf=15,min_samples_split=40)
#min_samples_leaf=15
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

[[1048    9]
 [   5 1115]]


0.99356913183279738

**Grid Search**

In [210]:
from sklearn.model_selection import GridSearchCV
#specify the parameters for wich we want to find the optimal values, give different options in dictionaries
parameters = [{'loss':["deviance","exponential"],'learning_rate': [0.1, 0.05, 0.2], 'n_estimators': [100,1000,2000], "max_depth":[1,3,5]}]
#estimator: the model
#param_grid: the list of parameters
#scoring: scoring metric
#cv: number of folds in k-fold cross validation
#n_jobs: -1 gives all the power available of the machine
grid_search = GridSearchCV(estimator = GradientBoostingClassifier(),
                           param_grid = parameters,
                           scoring = 'accuracy',
                           n_jobs = -1)
#fit
grid_search = grid_search.fit(X_train, y_train)
#get best accuracy score
best_accuracy = grid_search.best_score_
#best paramesters
best_parameters = grid_search.best_params_



In [211]:
best_parameters

{'learning_rate': 0.2,
 'loss': 'exponential',
 'max_depth': 1,
 'n_estimators': 2000}

In [213]:
from sklearn.ensemble import GradientBoostingClassifier
classifier = GradientBoostingClassifier(loss="exponential",learning_rate = .2, 
                                  n_estimators = 2000,max_depth=1,min_samples_leaf=15,min_samples_split=40)
#min_samples_leaf=15
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

[[1046   11]
 [   2 1118]]


0.99402847955902618

**Neural network**

In [215]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.layers import Dense, Dropout

In [267]:
model = Sequential()
model.add(Dense(256, input_dim=X_train.shape[1],activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))


model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

model.fit(X_train, y_train,
          epochs=100,
          batch_size=64)
score = model.evaluate(X_test, y_test, batch_size=128)

Epoch 1/100
8705/8705 [==============================] - 1s 68us/step - loss: 0.2008 - acc: 0.9205
Epoch 2/100
8705/8705 [==============================] - 0s 24us/step - loss: 0.0986 - acc: 0.9594
Epoch 3/100
8705/8705 [==============================] - 0s 23us/step - loss: 0.0655 - acc: 0.9755
Epoch 4/100
8705/8705 [==============================] - 0s 23us/step - loss: 0.0505 - acc: 0.9784
Epoch 5/100
8705/8705 [==============================] - 0s 23us/step - loss: 0.0424 - acc: 0.9821
Epoch 6/100
8705/8705 [==============================] - 0s 24us/step - loss: 0.0395 - acc: 0.9831
Epoch 7/100
8705/8705 [==============================] - 0s 23us/step - loss: 0.0340 - acc: 0.9867
Epoch 8/100
8705/8705 [==============================] - 0s 31us/step - loss: 0.0293 - acc: 0.9877
Epoch 9/100
8705/8705 [==============================] - 0s 26us/step - loss: 0.0288 - acc: 0.9895
Epoch 10/100
8705/8705 [==============================] - 0s 23us/step - loss: 0.0239 - acc: 0.9901
Epoch 11/

8705/8705 [==============================] - 0s 26us/step - loss: 0.0058 - acc: 0.9977
Epoch 84/100
8705/8705 [==============================] - 0s 23us/step - loss: 0.0062 - acc: 0.9976
Epoch 85/100
8705/8705 [==============================] - 0s 23us/step - loss: 0.0028 - acc: 0.9994
Epoch 86/100
8705/8705 [==============================] - 0s 25us/step - loss: 0.0048 - acc: 0.9989
Epoch 87/100
8705/8705 [==============================] - 0s 27us/step - loss: 0.0043 - acc: 0.9990
Epoch 88/100
8705/8705 [==============================] - 0s 26us/step - loss: 0.0076 - acc: 0.9982
Epoch 89/100
8705/8705 [==============================] - 0s 24us/step - loss: 0.0051 - acc: 0.9982
Epoch 90/100
8705/8705 [==============================] - 0s 25us/step - loss: 0.0053 - acc: 0.9986
Epoch 91/100
8705/8705 [==============================] - 0s 25us/step - loss: 0.0063 - acc: 0.9987
Epoch 92/100
8705/8705 [==============================] - 0s 28us/step - loss: 0.0082 - acc: 0.9983
Epoch 93/100


In [268]:
y_pred=model.predict(X_test)
y_pred1=[]
for i in range(0,len(y_pred)):
    y_pred1.append(np.round(y_pred[i][0]))
y_pred=np.array(y_pred1,dtype=np.int64)

In [269]:
print(accuracy_score(y_pred,y_test))
confusion_matrix(y_pred,y_test)

0.988056959118


array([[1040,    9],
       [  17, 1111]])

**Cross-validation**

In [275]:
from sklearn.cross_validation import cross_val_score
RFC = GradientBoostingClassifier(loss="exponential",learning_rate = .2, 
                                  n_estimators = 2000,max_depth=1,min_samples_leaf=15,min_samples_split=40)
y_pred = RFC.fit(X_train, y_train).predict(X_test)
cv_score = cross_val_score(RFC, X_test, y_test, scoring = 'accuracy', cv = 5)
print('CV Model Accuracy :' , cv_score.mean())
print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0],(y_test != y_pred).sum()))


CV Model Accuracy : 0.982549826004
Number of mislabeled points out of a total 2177 points : 13
